"""empty message

Revision ID: 19f1acfa82c7
Revises: cedb474fe6e5
Create Date: 2019-09-01 03:17:36.219951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f1acfa82c7'
down_revision = 'cedb474fe6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('Time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'Time')
    # ### end Alembic commands ###
