"""empty message

Revision ID: 82cdc4ae9313
Revises: 19f1acfa82c7
Create Date: 2019-09-01 03:48:22.622599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cdc4ae9313'
down_revision = '19f1acfa82c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Pass_Hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_Email'), 'user', ['Email'], unique=True)
    op.create_index(op.f('ix_user_Name'), 'user', ['Name'], unique=True)
    op.add_column('post', sa.Column('Body', sa.String(), nullable=True))
    op.create_index(op.f('ix_post_Time'), 'post', ['Time'], unique=False)
    op.drop_index('ix_post_Posts', table_name='post')
    op.drop_index('ix_post_Title', table_name='post')
    op.drop_index('ix_post_User', table_name='post')
    op.create_foreign_key(None, 'post', 'user', ['User'], ['id'])
    op.drop_column('post', 'Posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('Posts', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_index('ix_post_User', 'post', ['User'], unique=1)
    op.create_index('ix_post_Title', 'post', ['Title'], unique=1)
    op.create_index('ix_post_Posts', 'post', ['Posts'], unique=1)
    op.drop_index(op.f('ix_post_Time'), table_name='post')
    op.drop_column('post', 'Body')
    op.drop_index(op.f('ix_user_Name'), table_name='user')
    op.drop_index(op.f('ix_user_Email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
